name: 'oef_system'
version: '1.0.0'

profile: 'oef_system'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"

vars:
  lock_timeout_minutes: 3

flags:
  warn_error_options:
    silence:
      - UnusedResourceConfigPath

models:
  oef_system:
    +pre-hook: "{{process_prehook()}}"
    +post-hook: "{{process_posthook()}}"
    processing:
      +database: oef
      +materialized: table
      meta:
        +schema: meta
      src:
        +schema: src
        event:
          +_table_structure: event
          +cluster_by: ['date(event_time)']
          +incremental_strategy: insert
        history:
          +_rollback_days: 0
          +_table_structure: history
          +cluster_by: ['date(valid_to)']
          +incremental_predicates: 
            - "date(DBT_INTERNAL_DEST.valid_to) = date('9999-12-31')"
          +incremental_strategy: merge
      extsrc:
        +schema: extsrc
      extanl:
        +schema: extanl
        history:
          +materialized: incremental
          +_rollback_days: 0
          +_table_structure: history
          +cluster_by: ['date(valid_to)']
          +incremental_predicates: 
            - "date(DBT_INTERNAL_DEST.valid_to) = date('9999-12-31')"
          +incremental_strategy: merge
        snapshot:
    reporting:
      +database: reporting_db